import { ActionType } from "../action-types"

interface TOP_RATED_MOVIES_ACTIONS{
    type:ActionType.FETCH_TOP_RATED_MOVIES_REQUEST| ActionType.FETCH_TOP_RATED_MOVIES_SUCCESS |
    ActionType.FETCH_TRENDING_MOVIES_ERROR,
    payload?:any    
}
interface TRENDING_MOVIES_ACTIONS{
    type:ActionType.FETCH_TRENDING_MOVIES_REQUEST | ActionType.FETCH_TRENDING_MOVIES_SUCCESS | ActionType.FETCH_TRENDING_MOVIES_ERROR,
    payload?:any
}
interface ACTION_MOVIES_ACTIONS{
    type:ActionType.FETCH_ACTION_MOVIES_REQUEST | ActionType.FETCH_ACTION_MOVIES_SUCCESS | ActionType.FETCH_ACTION_MOVIES_ERROR,
    payload?:any
}
interface ANIMATION_MOVIES_ACTIONS{
    type:ActionType.FETCH_ANIMATION_MOVIES_REQUEST | ActionType.FETCH_ANIMATION_MOVIES_SUCCESS | ActionType.FETCH_ANIMATION_MOVIES_ERROR,
    payload?:any
}
interface COMEDY_MOVIES_ACTIONS{
    type:ActionType.FETCH_COMEDY_MOVIES_REQUEST | ActionType.FETCH_COMEDY_MOVIES_SUCCESS | ActionType.FETCH_COMEDY_MOVIES_ERROR,
    payload?:any
}
interface HORROR_MOVIES_ACTIONS{
    type:ActionType.FETCH_HORROR_MOVIES_REQUEST | ActionType.FETCH_HORROR_MOVIES_SUCCESS | ActionType.FETCH_HORROR_MOVIES_ERROR,
    payload?:any
}
interface LATEST_MOVIES_ACTIONS{
    type:ActionType.FETCH_LATEST_MOVIES_REQUEST | ActionType.FETCH_LATEST_MOVIES_SUCCESS | ActionType.FETCH_LATEST_MOVIES_ERROR,
    payload?:any
}
interface ROMANCE_MOVIES_ACTIONS{
    type:ActionType.FETCH_ROMANCE_MOVIES_REQUEST | ActionType.FETCH_ROMANCE_MOVIES_SUCCESS | ActionType.FETCH_ROMANCE_MOVIES_ERROR,
    payload?:any
}
interface UPCOMING_MOVIES_ACTIONS{
    type:ActionType.FETCH_UPCOMING_MOVIES_REQUEST | ActionType.FETCH_UPCOMING_MOVIES_SUCCESS | ActionType.FETCH_UPCOMING_MOVIES_ERROR,
    payload?:any
}
interface ADVENTURE_ACTIONS{
    type:ActionType.FETCH_ADVENTURE_MOVIES_REQUEST | ActionType.FETCH_ADVENTURE_MOVIES_SUCCESS | ActionType.FETCH_ADVENTURE_MOVIES_ERROR,
    payload?:any
}
interface POPULAR_MOVIES_ACTIONS{
    type:ActionType.FETCH_POPULAR_MOVIES_REQUEST | ActionType.FETCH_POPULAR_MOVIES_SUCCESS | ActionType.FETCH_POPULAR_MOVIES_ERROR,
    payload?:any
}
interface OPEN {
    type:ActionType.OPEN,
    payload?:any
}
export type action = OPEN | TOP_RATED_MOVIES_ACTIONS | TRENDING_MOVIES_ACTIONS |ACTION_MOVIES_ACTIONS | ADVENTURE_ACTIONS |ANIMATION_MOVIES_ACTIONS | 
    COMEDY_MOVIES_ACTIONS |HORROR_MOVIES_ACTIONS | LATEST_MOVIES_ACTIONS |POPULAR_MOVIES_ACTIONS | ROMANCE_MOVIES_ACTIONS |UPCOMING_MOVIES_ACTIONS 



