export enum MoviesTypes {
     // TOP_RATED_MOVIES
    FETCH_TOP_RATED_MOVIES_REQUEST='FETCH_TOP_RATED_MOVIES_REQUEST',
    FETCH_TOP_RATED_MOVIES_SUCCESS='FETCH_TOP_RATED_MOVIES_SUCCESS',
    FETCH_TOP_RATED_MOVIES_ERROR='FETCH_TOP_RATED_MOVIES_ERROR',
    //TRENDING_MOVIES
    FETCH_TRENDING_MOVIES_REQUEST='FETCH_TRENDING_MOVIES_REQUEST',
    FETCH_TRENDING_MOVIES_SUCCESS='FETCH_TRENDING_MOVIES_SUCCESS',
    FETCH_TRENDING_MOVIES_ERROR='FETCH_TRENDING_MOVIES_ERROR',
    LOAD_MORE_TRENDING_MOVIES_SUCCESS='LOAD_MORE_TRENDING_MOVIES_SUCCESS',
    //ACTION MOVIES
    FETCH_ACTION_MOVIES_REQUEST='FETCH_ACTION_MOVIES_REQUEST',
    FETCH_ACTION_MOVIES_SUCCESS='FETCH_ACTION_MOVIES_SUCCESS',
    FETCH_ACTION_MOVIES_ERROR='FETCH_ACTION_MOVIES_ERROR',
    //ANIMATION MOVIES
    FETCH_ANIMATION_MOVIES_REQUEST='FETCH_ANIMATION_MOVIES_REQUEST',
    FETCH_ANIMATION_MOVIES_SUCCESS='FETCH_ANIMATION_MOVIES_SUCCESS',
    FETCH_ANIMATION_MOVIES_ERROR='FETCH_ANIMATION_MOVIES_ERROR',
    //ROMANCE
    FETCH_ROMANCE_MOVIES_REQUEST='FETCH_ROMANCE_MOVIES_REQUEST',
    FETCH_ROMANCE_MOVIES_SUCCESS='FETCH_ROMANCE_MOVIES_SUCCESS',
    FETCH_ROMANCE_MOVIES_ERROR='FETCH_ROMANCE_MOVIES_ERROR',
    // HORROR
    FETCH_HORROR_MOVIES_REQUEST='FETCH_HORROR_MOVIES_REQUEST',
    FETCH_HORROR_MOVIES_SUCCESS='FETCH_HORROR_MOVIES_SUCCESS',
    FETCH_HORROR_MOVIES_ERROR='FETCH_HORROR_MOVIES_ERROR',
    //COMEDY
    FETCH_COMEDY_MOVIES_REQUEST='FETCH_COMEDY_MOVIES_REQUEST',
    FETCH_COMEDY_MOVIES_SUCCESS='FETCH_COMEDY_MOVIES_SUCCESS',
    FETCH_COMEDY_MOVIES_ERROR='FETCH_COMEDY_MOVIES_ERROR',
    // ADVENTURE
    FETCH_ADVENTURE_MOVIES_REQUEST='FETCH_ADVENTURE_MOVIES_REQUEST',
    FETCH_ADVENTURE_MOVIES_SUCCESS='FETCH_ADVENTURE_MOVIES_SUCCESS',
    FETCH_ADVENTURE_MOVIES_ERROR='FETCH_ADVENTURE_MOVIES_ERROR',
    // POPULAR
    FETCH_POPULAR_MOVIES_REQUEST='FETCH_POPULAR_MOVIES_REQUEST',
    FETCH_POPULAR_MOVIES_SUCCESS='FETCH_POPULAR_MOVIES_SUCCESS',
    FETCH_POPULAR_MOVIES_ERROR='FETCH_POPULAR_MOVIES_ERROR',
    // UPCOMING
    FETCH_UPCOMING_MOVIES_REQUEST='FETCH_UPCOMING_MOVIES_REQUEST',
    FETCH_UPCOMING_MOVIES_SUCCESS='FETCH_UPCOMING_MOVIES_SUCCESS',
    FETCH_UPCOMING_MOVIES_ERROR='FETCH_UPCOMING_MOVIES_ERROR',
    // LATEST
    FETCH_LATEST_MOVIES_REQUEST='FETCH_LATEST_MOVIES_REQUEST',
    FETCH_LATEST_MOVIES_SUCCESS='FETCH_LATEST_MOVIES_SUCCESS',
    FETCH_LATEST_MOVIES_ERROR='FETCH_LATEST_MOVIES_ERROR',
}