export enum TvShowsTypes {
    // TRENDING
    FETCH_TRENDING_TV_SHOWS_REQUEST = 'FETCH_TRENDING_TV_SHOWS_REQUEST',
    FETCH_TRENDING_TV_SHOWS_SUCCESS = 'FETCH_TRENDING_TV_SHOWS_SUCCESS',
    FETCH_TRENDING_TV_SHOWS_ERROR = 'FETCH_TRENDING_TV_SHOWS_ERROR',
    // ACTION
    FETCH_ACTION_TV_SHOWS_REQUEST = 'FETCH_ACTION_TV_SHOWS_REQUEST',
    FETCH_ACTION_TV_SHOWS_SUCCESS = 'FETCH_ACTION_TV_SHOWS_SUCCESS',
    FETCH_ACTION_TV_SHOWS_ERROR = 'FETCH_ACTION_TV_SHOWS_ERROR',
    // ANIMATION
    FETCH_ANIMATION_TV_SHOWS_REQUEST = 'FETCH_ANIMATION_TV_SHOWS_REQUEST',
    FETCH_ANIMATION_TV_SHOWS_SUCCESS = 'FETCH_ANIMATION_TV_SHOWS_SUCCESS',
    FETCH_ANIMATION_TV_SHOWS_ERROR = 'FETCH_ANIMATION_TV_SHOWS_ERROR',
    // COMEDY
    FETCH_COMEDY_TV_SHOWS_REQUEST = 'FETCH_COMEDY_TV_SHOWS_REQUEST',
    FETCH_COMEDY_TV_SHOWS_SUCCESS = 'FETCH_COMEDY_TV_SHOWS_SUCCESS',
    FETCH_COMEDY_TV_SHOWS_ERROR = 'FETCH_COMEDY_TV_SHOWS_ERROR',
    // CRIME
    FETCH_CRIME_TV_SHOWS_REQUEST = 'FETCH_CRIME_TV_SHOWS_REQUEST',
    FETCH_CRIME_TV_SHOWS_SUCCESS = 'FETCH_CRIME_TV_SHOWS_SUCCESS',
    FETCH_CRIME_TV_SHOWS_ERROR = 'FETCH_CRIME_TV_SHOWS_ERROR',
    // DOCUMENTARY
    FETCH_DOCUMENTARY_TV_SHOWS_REQUEST = 'FETCH_DOCUMENTARY_TV_SHOWS_REQUEST',
    FETCH_DOCUMENTARY_TV_SHOWS_SUCCESS = 'FETCH_DOCUMENTARY_TV_SHOWS_SUCCESS',
    FETCH_DOCUMENTARY_TV_SHOWS_ERROR = 'FETCH_DOCUMENTARY_TV_SHOWS_ERROR',
}